[package]
name = "contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.2.1"
near-contract-standards = "5.2.1"
near-sys = "0.2.2"
hex = "0.4"
